### ISSUE TITLE
Issue with fullscreen rendering

### ISSUE THREAD

**Issue by PranavSakthivel** [akshay5995/powerbi-report-component#129]
I'm not able to get the report to render fullscreen, even after adding height 100% to style options, App.css, and index.css. Any idea what could be causing this? Thank you.
![Github](https://user-images.githubusercontent.com/33013003/71602258-4b3b4980-2b0c-11ea-8698-f06f40b596a1.png)

**Comment by akshay5995** [comment]
@PranavSakthivel  

Try passing the style inline something like 

```js

<Report
  // Other props
   style={{
      height: '100%',
      border: '0',
      padding: '20px',
      background: '#eee'
    }}
/>

```

**Comment by akshay5995** [comment]
@PranavSakthivel Did it fix the issue ?

**Comment by PranavSakthivel** [comment]
Thanks for the help. I tried that with no luck, and went through the other issue that was opened a few months back. What I found worked was adding
`body > #root > div {
  height: 100vh;
}`
into App.js and that seemed to solve it. Probably not an issue with the component itself.
