### ISSUE TITLE
Power BI Sign-In button does nothing[Question]

### ISSUE THREAD

**Issue by ipaptim** [akshay5995/powerbi-report-component#145]
When the page comes up the first time comes up with a Power BI Sign-In screen with a Sign-In button.  When you click it, nothing happens.  Is there a way to have to prompt the user to Sign In or do they need to sign into Power BI outside of this page?

**Comment by akshay5995** [comment]
Are you using `secure` embed? Maybe this will help. https://powerbi.microsoft.com/en-us/blog/easily-embed-secure-power-bi-reports-in-your-internal-portals-or-websites/
