### ISSUE TITLE
[FEATURE] Add onError event.

### ISSUE THREAD

**Issue by ddivita** [akshay5995/powerbi-report-component#155]
Would be nice if this had an `onError` event. It would help with [overriding the error experience](https://github.com/microsoft/PowerBI-JavaScript/wiki/Overriding-Error-Experience).

**Comment by akshay5995** [comment]
Will do it in a day or two. 👍

**Comment by akshay5995** [comment]
Fixed PR (https://github.com/akshay5995/powerbi-report-component/pull/156). Thanks @ddivita 🎉
