### ISSUE TITLE
[BUG] Unable to embed tile

### ISSUE THREAD

**Issue by rachitharlalka** [akshay5995/powerbi-report-component#174]
I am trying to embed a tile but it doesn't load. 

`const report2 = (
              <Report
                embedType="dashboard" // or "dashboard"
                tokenType="Embed" // or "Aad"
                accessToken={embedTileConfig.embedToken.token} // accessToken goes here
                embedUrl={embedTileConfig.embedUrl} // embedUrl goes here
                embedId={embedTileConfig.id} // Report or Dashboard ID goes here
                dashboardId={embedTileConfig.dashboardId}
                permissions="View" // or "View"
                onLoad={this.onEmbedded}
              />
            );`

**Comment by akshay5995** [comment]
There's a PR for it. https://github.com/akshay5995/powerbi-report-component/pull/57. I've not gotten enough time to work on it. I'll try to fix over the weekend.

**Comment by rachitharlalka** [comment]
Thank you Akshay. It would be another great help. :)

**Comment by akshay5995** [comment]
@rachitharlalka Use version `1.8.0` for the new mode

**Comment by rachitharlalka** [comment]
Working like a charm. Thank you so much @akshay5995. :)
