### ISSUE TITLE
[BUG] Event gets triggered only for the last embedded report

### ISSUE THREAD

**Issue by rachitharlalka** [akshay5995/powerbi-report-component#175]
I have embedded multiple reports in the same page which all have some events. But the event get triggered only for the last added report and not for all. Please help.

**Comment by akshay5995** [comment]
The report internally uses `powerbi` global object. I think that would mean their Microsoft's fore lib implementation is binded only to the last embedded report. Let me look into it and give more details. Is there a reason that your using multiple reports ?

**Comment by akshay5995** [comment]
Hi, I found a similar issue on [stackoverflow](https://stackoverflow.com/questions/50718940/calling-powerbi-embed-multiple-times-at-the-same-time-produces-an-error).  So I fixed your issue can you try and check with new package version `1.7.2`.

**Comment by rachitharlalka** [comment]
Thank you Akshay for the quick help. The reason behind using multiple report is to embed tiles based on user role.

**Comment by akshay5995** [comment]
Oh okay, Can you test it on your end? And re-open if not fixed.

**Comment by rachitharlalka** [comment]
I was testing this only. It's working fine but not sure why i am getting too many errors in console.

ERROR Error: Uncaught (in promise): Esri is not supported in Embedded scenario. 
ERROR Error: Uncaught (in promise): Error
ERROR TypeError: Cannot read property 'reject' of undefined
 All errors are related to dashboardEmbed.min.js
<img width="939" alt="embed-errors" src="https://user-images.githubusercontent.com/12514908/78376568-257e7e80-75ec-11ea-8144-9d8b1191719f.PNG">

**Comment by akshay5995** [comment]
@rachitharlalka It's error thrown by the `powerbi` js lib by Microsoft.  You can see it in stacktrace `dashboard.min.js`.

**Comment by akshay5995** [comment]
Please feel free to email me directly. I'll see if I can help you out.

**Comment by rachitharlalka** [comment]
Sure. Thanks for the help. I ma trying to embed tile and report. But because tile option is not available, so embedded dashboard with single tile.
