### ISSUE TITLE
Gray border coming with report

### ISSUE THREAD

**Issue by neerajnarayanankp** [akshay5995/powerbi-report-component#187]
When Report is loaded, a grey border is coming . How to get rid of this ?

Expectation:
Only report content should be loaded, instead the a gray border of iframe is coming.

**Comment by akshay5995** [comment]
@neerajnarayanankp Can you send me a screenshot of an example ?

**Comment by akshay5995** [comment]
Did you try passing in `style` prop?

```
<Report {..otherProps} 
   style={{
        height: '100%',
        border: '0',
        padding: '20px',
        background: '#eee'
   }} />
```

**Comment by neerajnarayanankp** [comment]
@akshay5995 .sorry i am not able to share screenshot since the data is somewhat confidential.
i tried those style params , but still a boder is there.
But on finding the underlying iframe and changing the boder propery to 0 by inspecting the element , the border is removing.
is this a issue from pbi itself. i am not sure.

**Comment by akshay5995** [comment]
Maybe, Use can use `css selectors` to remove the border bu overriding the if the `div` is within the iframe.

**Comment by neerajnarayanankp** [comment]
@akshay5995 got my issue resolved  by providing 
.report > iframe {
  border: 0 !important;
}
Thank you
