### ISSUE TITLE
Datasetbinding in reports

### ISSUE THREAD

**Issue by rachitharlalka** [akshay5995/powerbi-report-component#191]
Please add the dynamic dataset binding feature while embedding reports. It is used to connect with different datasets dynamically while having only one report. Below is the URL for refernce.

[Here](https://github.com/microsoft/PowerBI-JavaScript/wiki/Dynamic-Binding)

**Comment by akshay5995** [comment]
Will do it today 👍

**Comment by rachitharlalka** [comment]
Thank you Akshay. Really appreciate your help!

**Comment by akshay5995** [comment]
@rachitharlalka Please use `datasetId` prop to pass in your dataset id.

```<Report datasetId="your-dataset-id" {...otherProps} />```

**Comment by akshay5995** [comment]
@rachitharlalka feel free to reopen if not fixed

**Comment by rachitharlalka** [comment]
It's working as expected. Thank you Akshay and apologies for not replying yesterday as was busy with some crucial work.

**Comment by akshay5995** [comment]
No problems, Thanks for confirming!
