### ISSUE TITLE
[BUG] Embed reset function undefined

### ISSUE THREAD

**Issue by victorkurauchi** [akshay5995/powerbi-report-component#196]
**Describe the bug**
If you go to `Embed.jsx` in the `didUpdate()` method, you notice that there is no `this.reset()` method, unless it's from React itself but couldn't find docs. I even tried to force the this.reset before the first if

**To Reproduce**
1. Go to `Embed.jsx`
2. Move this.reset() to first line in the `didUpdate` method
3. See error "reset is not a function"

**Expected behavior**
We should be able to reset the component?

**Screenshots**
<img width="449" alt="Screen Shot 2020-04-24 at 6 38 58 pm" src="https://user-images.githubusercontent.com/2061031/80258976-e8416580-865a-11ea-9729-bcd319d7f208.png">

Is that expected or should have a reset component/report method in place?
Thanks

**Comment by akshay5995** [comment]
@victorkurauchi  This is the existing code. We check for `this.component` before you can reset. If `this.component` is `null` you can't reset right?
``` componentDidUpdate() {
    const errors = validateConfig(this.state);
    if (!errors) {
      return this.embed(this.state);
    } else if (this.component !== null) {
      this.reset();
    }
    return null;
  }
```

**Comment by akshay5995** [comment]
What do want to accomplish with the change you specified?

**Comment by victorkurauchi** [comment]
I meant, it looks like this.reset() function is never present, so even when we get to the point where the condition meets criteria, we'll have a crash... Or am I missing something?

```
else if (this.component !== null) {
      this.reset(); // not a function
    } 
```

**Comment by akshay5995** [comment]
True, No you're not. I don't remember why it was added. I'll remove it.

**Comment by akshay5995** [comment]
I think older version of Microsoft powerbi library had a reset function. And it probably should've been 'this.component.reset()' as that part was never changed for long time. I don't remember.

Apart from code cleanup is this causing any issues while using ? @victorkurauchi

**Comment by victorkurauchi** [comment]
No @akshay5995 , apart from this cleanup we're good :) Just noticed because yesterday I was debugging my app and it came down to the component codebase haha.

Thanks, if you need I can open a PR.

**Comment by akshay5995** [comment]
Sure, Please go ahead and open a PR 🙏. Thanks for reporting 😄

**Comment by akshay5995** [comment]
Removed in the newly refactored version.
