### ISSUE TITLE
[Refactor] Docs/ Demo page

### ISSUE THREAD

**Issue by akshay5995** [akshay5995/powerbi-report-component#202]
Docs component (demo) app has become a gigantic mess with more fields and is not so easy to navigate or use.

Refactor into multiple components.

**Comment by akshay5995** [comment]
@satya64 should be a only docs change . Let's not have a milestone with versions for docs change 😄

**Comment by satya64** [comment]
> @satya64 should be a only docs change . Let's not have a milestone with versions for docs change 😄

- Okay 😀
