### ISSUE TITLE
Page breaks while resizing the window

### ISSUE THREAD

**Issue by neerajnarayanankp** [akshay5995/powerbi-report-component#209]
I am using multiple reports in same page by using pageName property . But on window resize the page breaks with the following error.

`powerbi.js:499 Uncaught Error: Attempted to embed using config {"type":"report","tokenType":1,"accessToken":"accestoken","embedUrl":"embedurl","id":"id","pageName":"pageName","permissions":7,"settings":{"filterPaneEnabled":false,"navContentPaneEnabled":false}} on element <div class="report" id="73c79e38-0ace-446c-a5a2-7af4415d4a51" style="height: 100%; border: 0px; width: 100%; overflow: scroll;"><iframe src="uri scrolling="no" allowfullscreen="true" style="width: 100%; height: 100%;"></iframe></div> which already has embedded comopnent associated, but could not find the existing comopnent in the list of active components. This could indicate the embeds list is out of sync with the DOM, or the component is referencing the incorrect HTML element.`

Please help me on this.

**Comment by akshay5995** [comment]
@neerajnarayanankp I'll take a look at it tonight.

**Comment by akshay5995** [comment]
@neerajnarayanankp `embedId` for both are the same ?

**Comment by neerajnarayanankp** [comment]
@akshay5995  yes . `embedId` is same for both.only pageName is different .

**Comment by akshay5995** [comment]
Will merge and release new version. `2.0.2`

**Comment by akshay5995** [comment]
@neerajnarayanankp Latest version `2.0.2` should fix your issue. Please feel free to reopen if it's not fixed.

**Comment by neerajnarayanankp** [comment]
@akshay5995 thanks for the super quick reply and fix  👍 . 
Issue fixed !!!!
