### ISSUE TITLE
[BUG] Demo - removing config props from fields throwing error

### ISSUE THREAD

**Issue by satya64** [akshay5995/powerbi-report-component#211]
Description:

In the demo page, if we enter embed fields and run, report comes up on the left pane. If we remove one of the entered config value, say Embed Id, it should reset the left pane, but it is causing entire screen to go blank.

Reproduction steps:

1. Go to 'https://akshay5995.github.io/powerbi-report-component/'
2. Select Embed Type 'report' and embed mode 'view'
3. Fill in Token, Embed Url, Embed Id and run
4. Report will appear in the left pane
5. Next, delete one of the above values from the field, example, remove value Token field
6. Then the entire screen goes blank

Expected:
It should not go blank. Instead, the right pane should stay same and left pane should reset to default view with "Report will be displayed in this section"

**Comment by akshay5995** [comment]
Refactor should fix it. Closing. Reopen if it's not fixed.
