### ISSUE TITLE
[BUG]  Error 403 when running application

### ISSUE THREAD

**Issue by paulo205** [akshay5995/powerbi-report-component#222]
Good afternoon.
I am trying the following problem. I make a request to an api where I receive the embedtoken and pass the properties. but when i run the application i get a 403 error.

code:
![codigo](https://user-images.githubusercontent.com/65562932/82250087-3b889a00-9921-11ea-9bd0-a14a39cb63d8.jpg)

error:
![error](https://user-images.githubusercontent.com/65562932/82250125-493e1f80-9921-11ea-8465-6d86aa288541.jpg)

**Comment by akshay5995** [comment]
Hi @paulo205 , I see that your your `this.state.list[1]` is set asynchronously i.e, Which means when your render function is called `this.state.list[1]` is `undefined` . You can handle it by doing something like this.


```javascript
render() {
   return(
     <Main {...headerProps}>
         { !!this,state.list[1] && 
                <Report tokenType="Embed"
                     id={this.state.list[1].id} 
                     accessToken={this.state.list[1].EmbedToken}
                    // other props go here
                  />}
    );
}
```

**Comment by paulo205** [comment]
Thanks, sorry to bother you with something so simple. But as I am still learning react, I have difficulties in some concepts.

**Comment by akshay5995** [comment]
No problem! Everyone has to go through the learning curve. Feel free to reach out if you have more doubts. All the best!
