### ISSUE TITLE
Report update

### ISSUE THREAD

**Issue by paulo205** [akshay5995/powerbi-report-component#224]
Hello good afternoon.
I have another question, I'm looking for the id and embed toke through a request with axios. The request is triggered when I click on the link. The first report loads normally, but if I click on another one it does not update the iframe how can I fix it.

![Sem título](https://user-images.githubusercontent.com/65562932/82842678-d1d43700-9eb0-11ea-9ec9-5f236ee26609.jpg)

```
import Main from '../template/Main'
import React, { Component } from 'react'
import { Report } from 'powerbi-report-component'
import axios from 'axios'


const headerPros = {
  title: 'Relatorio',
  subtitle: 'Exibição de Relatorios'
}

const baseUrlReports = 'http://localhost:3001/api/v1/groups/'
const baseUrlWorkspace = 'http://localhost:3001/api/v1/usuarios'

export default class Reports extends Component {
  constructor(props) {
    super(props)
    this.state = { 
      idworkspace: '',
      workspaceDb: [],
      values: [],
      report: [] 
    }

    this.getReports = this.getReports.bind(this)
    this.getReport = this.getReport.bind(this)
    this.renderReports = this.renderReports.bind(this)
    this.renderLi = this.renderLi.bind(this)
  }

  getReport(event) {
    event.preventDefault()
    let e = event.target.href

    axios.get(e)
      .then(response => {
        // handle success 
        this.setState({report: response.data})
    })
  }

  getReports(event) {
    let e = event.target.value
    
    this.setState({idworkspace: e})
    
    axios.get(baseUrlReports + e)
      .then(response => {
        // handle success
        this.setState({values: response.data.value})
      })
  }

  renderReports(event) {
    return ( 
      <ul class="m-2">
        {this.renderLi(event)}
      </ul>
    )
  }

  renderLi(event) {
    const lista = {
      listStyle: "none"
    }

    return this.state.values.map(data => {
      return (
        <li key={data.id} style={lista}><a href={"http://localhost:3001/api/v1/groups/" + this.state.idworkspace + "/report/" + data.id} onClick={this.getReport}>{data.name}</a></li>
      )
    })
  }

  componentWillMount() {
    axios(baseUrlWorkspace)
    .then(response => {
      // handle success
      //console.log(response)
      this.setState({workspaceDb: response.data})
    })
  }

  renderWorkspaces() {
    return(
      <select onChange={this.getReports}>
        <option value="oi">Escolha um Worspace</option>
        {this.renderOption()}
      </select>
    )
  }
 
  renderOption() {
    return this.state.workspaceDb.map(data => {
      return (
        <option key={data.idworkspacesusurios} value={data.identworkspace} >{data.workspace}</option>
      )
    })
  }

  render() {
    const reportStyle = {
      // style object for report component
      width: "100%",
      height: "90vh"
    }

    const floatRight = {
      width: "79%",
      marginBottom: "10px"
    }

    const floatLeft = {
      width: "20%"
    }

    return (
      <Main {...headerPros}>
        <div class="float-left" style={floatLeft}>
          <div class="card">
            <div class="card-header">
              <div class="float-left fa fa-bar-chart"></div>
              <div class="leftNavTitle leftNavItem">Grupos de trabalho</div>
            </div>
            {this.renderWorkspaces()}
          </div>
        
          <div class="card">
            <div class="card-header">
              <div class="float-left fa fa-bar-chart"></div>
              <div class="leftNavTitle leftNavItem">Relatorios</div>
            </div>
            {this.renderReports()}
          </div>
        </div>
        <div class="float-right" style={floatRight}>
        { !!this.state.report[0] && !!this.state.report[1] &&
          <Report
            tokenType="Embed" // "Aad"
            accessToken={this.state.report[1].EmbedToken} // accessToken goes here
            embedUrl="https://app.powerbi.com/reportEmbed" // embedUrl goes here
            embedId={this.state.report[0].id} // report or dashboard Id goes here
            pageName="" // set as current page of the report
            reportMode="view" // open report in a particular mode view/edit/create
            permissions="All"
            style={reportStyle}
          />}
          </div>
      </Main>
    );
  }
}
```

**Comment by akshay5995** [comment]
`Report` needs to unmount before you can update this configuration.
So, You can do something like if you have a different report ids. You can unmount using something like `loading` boolean. 

Have a state value called `loading` and when you make the call to switch the workspace make it `true` and when you get the response along with the configuration make `loading` as `false`.

You can use it like this.

Inside render:

```
  {!loading && <Report  ...{yourProps} />
```

**Comment by paulo205** [comment]
I tried it like that, but it doesn't render anything.
what am I doing wrong.

export default class Reports extends Component {
  constructor(props) {
    super(props)
    this.state = { 
      loading: true,
      idworkspace: '',
      workspaceDb: [],
      values: [],
      report: []
    }

    this.getReports = this.getReports.bind(this)
    this.getReport = this.getReport.bind(this)
    
    this.report = null
  }

  getReport(event) {
    event.preventDefault()
    let e = event.target.href

    axios.get(e)
      .then(response => {
        // handle success 
        this.setState({report: response.data, loading: false})
    })
  }

  getReports(event) {
    let e = event.target.value
    
    this.setState({idworkspace: e})
    
    axios.get(baseUrlReports + e)
      .then(response => {
        // handle success
        this.setState({values: response.data.value})
      })
  }

  
  renderReports(event) {
    return ( 
      <ul class="m-2">
        {this.renderLi(event)}
      </ul>
    )
  }
  
  renderLi(event) {
    const lista = {
      listStyle: "none"
    }
    
    return this.state.values.map(data => {
      return (
        <li key={data.id} style={lista}><a href={"http://localhost:3001/api/v1/groups/" + this.state.idworkspace + "/report/" + data.id} onClick={this.getReport}>{data.name}</a></li>
      )
    })
  }
  
  componentWillMount() {
    axios(baseUrlWorkspace)
    .then(response => {
      // handle success
      //console.log(response)
      this.setState({workspaceDb: response.data})
    })
  }
  
  renderWorkspaces() {
    return(
      <select onChange={this.getReports}>
        <option value="oi">Escolha um Worspace</option>
        {this.renderOption()}
      </select>
    )
  }
  
  renderOption() {
    return this.state.workspaceDb.map(data => {
      return (
        <option key={data.idworkspacesusurios} value={data.identworkspace} >{data.workspace}</option>
        )
      })
    }
    
    handleReportLoad = (report) => {
      this.report = report; // get the report object from callback and store it.
    }
    
    handleReportRender = (report) => {
      this.report = report; // get the report object from callback and store it.
    }
    
    setFullscreen = () => {
      if(this.report) this.report.fullscreen();
    }
    
    printReport = () => {
      if(this.report) this.report.print();
    }
    

    render() {
      const reportStyle = {
      // style object for report component
      width: "100%",
      height: "90vh"
    }

    const floatRight = {
      width: "79%",
      marginBottom: "10px"
    }

    const floatLeft = {
      width: "20%"
    }
     
    const dados = {
      tokenType:"Embed", // "Aad"
      accessToken: !!this.state.report[1] && this.state.report[1].EmbedToken, // accessToken goes here
      embedUrl: "https://app.powerbi.com/reportEmbed", // embedUrl goes here
      embedId: !!this.state.report[0] && this.state.report[0].id, // report or dashboard Id goes here
      pageName: "", // set as current page of the report
      reportMode: "view", // open report in a particular mode view/edit/create
      permissions: "All",
      style: reportStyle,
      onLoad: this.handleReportLoad,
      onRender: this.handleReportRender
    }

    return (
      <Main {...headerPros}>
        <div class="float-left" style={floatLeft}>
          <div class="card">
            <div class="card-header">
              <div class="float-left fa fa-bar-chart"></div>
              <div class="leftNavTitle leftNavItem">Grupos de trabalho</div>
            </div>
            {this.renderWorkspaces()}
          </div>
        
          <div class="card">
            <div class="card-header">
              <div class="float-left fa fa-bar-chart"></div>
              <div class="leftNavTitle leftNavItem">Relatorios</div>
            </div>
            {this.renderReports()}
          </div>
        </div>
        <div class="float-right" style={floatRight}>
          <button onClick={this.setFullscreen} class="btn btn-sm"><i class="fa fa-expand"></i>Fullscreen</button>
          <button onClick={this.printReport} class="btn btn-sm"><i class="fa fa-print"></i>Print</button>
        
          {!this.state.loading &&  <Report {...dados}   />}
          </div>
      </Main>
    );
  }
}

**Comment by akshay5995** [comment]
@paulo205,  https://dev.to/torianne02/componentwillmount-vs-componentdidmount-5f0n. Prefer using `componentDidMount` for anything that has to hydrate your state. Also, `componentWillMount` is deprecated in the latest versions of React. 

```  
componentDidMount() {
    axios(baseUrlWorkspace)
    .then(response => {
      // handle success
      //console.log(response)
      this.setState({workspaceDb: response.data , loading: false })
    })
  }
```
Make sure you set loading as `true` before you make the `axios`. And once you get the response in `finally` set loading as `false`.

```
getReports(event) {
    let e = event.target.value
    
    this.setState({idworkspace: e, loading: true })
    
    axios.get(baseUrlReports + e)
      .then(response => {
        // handle success
        this.setState({values: response.data.value})
      }).finally(() => { this.setState({ loading: false }))
  }
```

**Comment by paulo205** [comment]
thank you worked.
