### ISSUE TITLE
[FEATURE] typescript support

### ISSUE THREAD

**Issue by belozer-ti** [akshay5995/powerbi-report-component#227]
**Is your feature request related to a problem? Please describe.**
We using TypeScript in our project. Using this library adds a little inconvenience, because we need to write custom `d.ts` files, which may not correspond to reality after updating the library.

**Describe the solution you'd like**
Availability of `d.ts` files for all components in the library

**Comment by akshay5995** [comment]
@belozer-ti  I'll pick it up this weekend. Thanks for raising it.

**Comment by akshay5995** [comment]
@belozer-ti added support. Re-open if you're still facing issues.

**Comment by belozer-ti** [comment]
@akshay5995 thanks! I upgraded package to 2.2.0 version and have the same problems

![image](https://user-images.githubusercontent.com/61135195/83364396-c2ba2100-a3a9-11ea-8d74-467a3fa7ba1a.png)

```
Module '"../../../../../../node_modules/powerbi-report-component/lib/types"' has no exported member 'Report'.
Module '"../../../../../../node_modules/powerbi-report-component/lib/types"' has no exported member 'Dashboard'.
```

**Comment by akshay5995** [comment]
`import { Report } from 'powerbi-report-component/lib';` @belozer-ti try this.

**Comment by akshay5995** [comment]
Reopening to track import issues.

### Workaround for version `2.2.0` is `import { Report } from 'powerbi-report-component/lib';`

**Comment by akshay5995** [comment]
@belozer-ti Should be fixed in `2.2.1`.

**Comment by belozer-ti** [comment]
@akshay5995 why prop style in Dashboard declared as `string`, in Report declared as `any`. After all, it use the Embed component, which used in the property `style` of  `div` element.

It `React.CSSProperties` type
https://github.com/akshay5995/powerbi-report-component/blob/master/src/lib/Embed.tsx

**Comment by akshay5995** [comment]
@belozer-ti My bad. Fixed in the latest version `2.2.2` . It was by mistake.

**Comment by belozer-ti** [comment]
@akshay5995 I don't notice any critical problems yet. Thanks!

**Comment by akshay5995** [comment]
Thanks @belozer-ti . Please feel free to reopen this issue. If you find any issue.
