### ISSUE TITLE
[FEATURE] Better docs for settings object

### ISSUE THREAD

**Issue by MadsMadsDk** [akshay5995/powerbi-report-component#243]
I'm currently trying to implement a mobile view for an embedded report, but I think it's not really clear as to which settings are available on the `settings`-property of the `hooks` implementation. 

Currently, I'm just struggling with what I can pass to the `layoutType` property, but I could imagine it would be neat with a reference of which parameters are available, and what they do, both for me and for other developers :)

Otherwise, thanks for a super cool package. Really useful, and love the hooks implementation. Cheers!

**Comment by akshay5995** [comment]
Thanks @MadsMadsDk. I'll add the docs.

**Comment by akshay5995** [comment]
@MadsMadsDk Hope this helps https://github.com/akshay5995/powerbi-report-component#passing-in-custom-layout-for-usereport-hook

**Comment by akshay5995** [comment]
@MadsMadsDk Can I close this?
