### ISSUE TITLE
[BUG] onPageChange

### ISSUE THREAD

**Issue by timothyeash** [akshay5995/powerbi-report-component#254]
**Describe the bug**
When clicking on the page tabs at the bottom of a PowerBI report, the event onPageChange doesn't fire. I have another event "onSelectData" that does work.

  const handleDataSelected = (data) => {
    console.log("data selected", data);
  }
  const handlePageChange = (data) => {
    console.log("page changed", data);
  }

        <div key={reportId} className={loading !== true ? 'col-sm-12' : 'col-sm-12 loading-delete'}>
          <Report
            className={reportId}
            embedType="report"
            tokenType="Embed"
            pageName={reportId}
            accessToken={config.embedToken}
            embedUrl={config.embedUrl}
            embedId={config.id}
            permissions="All"
            onLoad={onLoadAndSetTokenListener}
            onSelectData={handleDataSelected}
            onTileClicked={handleTileClicked}
            onPageChange={handlePageChange}
            style={{
              height: '90vh',
              width: '100%',
              display: 'block',
              top: '0',
              left: '0',
              position: 'absolute',
              border: '0',
              padding: '20px',
              background: '#fff',
              zIndex: '1',
            }}
          />
        </div>

**Comment by akshay5995** [comment]
@timothyeash I can't reproduce it.

**Comment by akshay5995** [comment]
![image](https://user-images.githubusercontent.com/13801224/84414252-edbf3300-ac3b-11ea-84df-eeda9f2fd7ff.png)

**Comment by timothyeash** [comment]
I didn't want to tag it as a BUG has I am sure you guys have tested this simple feature. Probably can close this as clearly it works.

**Comment by akshay5995** [comment]
https://codesandbox.io/s/weathered-pine-d3bt4. Sandbox link for your reference.
