### ISSUE TITLE
[BUG] Support EditMode in useReport hook

### ISSUE THREAD

**Issue by CristianWesleyFront** [akshay5995/powerbi-report-component#264]
**Describe the bug**
I can't set "edit mode" when I use PowerBi component with hooks, they just show me report on view mode. When I put reportMode to edit this not works and show me again on view mode.  I also can't use onLoad function to use switchMode to edit like I use when not using with hooks.

**To Reproduce**
 const myReportConfig = {
    embedType: 'report',
    tokenType: 'AccessToken',
    permissions: 'All',
    accessToken: accessToken,
    embedUrl: embedUrl,
    embedId: embedId,
    extraSettings: {
      filterPaneEnabled: false,
      navContentPaneEnabled: false,
    },
    reportMode: 'edit',
  };

**Expected behavior**
show me report on edit mode

**Screenshots**
![image](https://user-images.githubusercontent.com/26757758/86487693-292db880-bd35-11ea-9408-6884a6368797.png)

**Additional context**
No have.

**Comment by akshay5995** [comment]
@CristianWesleyFront You can upgrade the package to version `2.2.4`. You can see the codesandbox [here](https://codesandbox.io/s/green-sky-bmj91?file=/src/App.js).

**Comment by akshay5995** [comment]
@CristianWesleyFront repoen this if it's not foxed.
