### ISSUE TITLE
[FEATURE] Add 'Report Visual' component

### ISSUE THREAD

**Issue by RossPauly** [akshay5995/powerbi-report-component#268]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There should be another component for Report Visuals. Tiles and Reports don't accept visual name so page visuals can't be rendered

**Describe alternatives you've considered**

**Comment by akshay5995** [comment]
@RossPauly added `ReportVisual` component. Please refer usage in the README. https://github.com/akshay5995/powerbi-report-component#new-usage-for-reportvisual

**Comment by akshay5995** [comment]
Version `2.4.0`
