### ISSUE TITLE
[BUG] ReportVisual datas 

### ISSUE THREAD

**Issue by plopcodes** [akshay5995/powerbi-report-component#282]
**Describe the bug**
Hi, as we said I am opening an issue regarding the ReportVisual component. Basically, I have a React app that is using two ReportVisual component on the same page. Both of those ReportVisual are rendering the Power Bi visual very well, no problem at all. However, both of the visuals are on the same report on power bi and both have interaction with each other (i.e if I do click on visual A, it does filter the data on the visual B). Unfortunately, it is not working on my test. 

Thanks a lot again for your work.

**To Reproduce**
1. Generate a report on power bi with two visual linked
2. Use this lib
3. Create two ReportVisual components with all the attributes (datasetid, reportid, visualid, accesstoken, etc)
4. Click and see the problem

Here is my code: 
```
return (
      <div className="root">
        <ReportVisual
          tokenType="Aad" // "Aad"
          accessToken="MYACCESSTOKEN" // accessToken goes here
          embedUrl="MYEMBEDURL" // embedUrl goes here
          embedId="MYEMBEDID" // report or dashboard Id goes here
          pageName="ReportSection" // set as current page of the report
          reportMode="View" // open report in a particular mode View/Edit/Create
          datasetId="MYDATASETID" // required for reportMode = "Create" and optional for dynamic databinding in report on View mode
          groupId="MYGROUPID" // optional. Used when reportMode = "Create" and to chose the target workspace when the dataset is shared.
          visualName="MYVISUALNAME_1"
          extraSettings={extraSettings}
          permissions="View" // View, For "Edit" mode permissions should be "All"
          style={reportStyle}
        />
        <ReportVisual
          tokenType="Aad" // "Aad"
          accessToken="MYACCESSTOKEN" // accessToken goes here
          embedUrl="MYEMBEDURL" // embedUrl goes here
          embedId="MYEMBEDID" // report or dashboard Id goes here
          pageName="ReportSection" // set as current page of the report
          reportMode="View" // open report in a particular mode View/Edit/Create
          datasetId="MYDATASETID" // required for reportMode = "Create" and optional for dynamic databinding in report on View mode
          groupId="MYGROUPID" // optional. Used when reportMode = "Create" and to chose the target workspace when the dataset is shared.
          visualName="MYVISUALNAME_2"
          extraSettings={extraSettings}
          permissions="View" // View, For "Edit" mode permissions should be "All"
          style={reportStyle}
        />
      </div>
    );
```

**Comment by akshay5995** [comment]
Hi @plopcodes,

Are you using `ReportVisual` or `Report` ?

```import { ReportVisual } from 'powerbi-report-component';

// inside render
<ReportVisual
  tokenType={tokenType}
  accessToken={accessToken}
  embedUrl={embedUrl}
  embedId={embedId}
  pageName={pageName}
  visualName={visualName}
  style={style} // style tile for report component
  onSelectData={(data) => {
    console.log('Data from ReportVisual', data);
  }}
  onLoad={(data) => {
    console.log('ReportVisual loaded', data);
  }}
  onRender={(data) => {
    console.log('ReportVisual rendered', data);
  }}
/>```

**Comment by akshay5995** [comment]
I can't reproduce it. Please see https://codesandbox.io/s/goofy-agnesi-7ssrp?file=/src/App.js

**Comment by plopcodes** [comment]
Hi @akshay5995 

Thanks for your time, I'm using `ReportVisual` but I tried both. 

I can't see the result of your code because the access tokens got expired I guess. I took your code and I did try locally but I have the same result. Maybe I wasn't super clear regarding my problem, here is a better description.

Here is the result of my work on PowerBi : 
<img width="885" alt="Capture d’écran 2020-08-02 à 14 32 01" src="https://user-images.githubusercontent.com/63913542/89123136-4806a280-d4cd-11ea-9ece-67f573c6a6dd.png">

Let say that the "circle" and the "lines" are two different visuals, when I click on one color of the circle, it will have an impact on the lines. For example, if I do click on the yellow part of the circle, it will filter the visual on the right by highlighting the yellow line. Those filters/reactions, are done on PowerBi, not through the code.

Then, in the code, I used your `ReportVisual` component in order to embed those two separately to add some css around etc. It is working well, however, if I click on the yellow part of the circle, it does not filter the other visual. 

I hope it is more clear, if there is any problem don't hesitate to contact me. 

Thanks a lot for your time.

**Comment by muthu1712** [comment]
Hi @plopcodes ,

I guess when you use `ReportVisual` , it becomes a completely independent component. It doesn't look for filters in other `ReportVisual` rendered in the same page.

If you need the Visuals to communicate with each other, then they must be rendered together as a Report only.

One more suggestion is that to probably handle the filtering manually via code by leveraging the getFilters and setFilters. But this means that all filtering logic in the current page needs to be handled meticulously.

**Comment by plopcodes** [comment]
HI @muthu1712,

That's exactly what I was thinking as well, make sense for me. 

I will close the issue then. Thank you

**Comment by plopcodes** [comment]
work as designed.
