### ISSUE TITLE
When a 2nd report loaded, error occurs

### ISSUE THREAD

**Issue by nissan** [akshay5995/powerbi-report-component#3]
I have a component which renders a PowerBi report using the powerbi-report-component and the props passed to it containing the reportId and groupId. Code inside the component gets the PBItoken based on the user's access token and adds filters appropriately.

However, when a user selects a new report from the menu (so Route does not change but reportId prop value changes), the new report does not load, even though componentDidUpdate() detects the changed prop and re-runs the request for a PBIToken initially done in componentDidMount (which will not fire again with a change of props) before loading the page.

Is this an error in my technique for applying the code? Or in the code itself?

**Comment by nissan** [comment]
Ok, I figured this out. You need to have a `key={this.state.accessToken}` that matches to the `accessToken` parameter, so that when `componentDidUpdate` is called and the PBI access token regenerated for the new report, the diff on the DOM that React does detects the change and re-renders the Report component with the new parameters. 

One lagging issue still though is that there is a 3-5 second period between when the prop changes and when the Report is re-rendered where the PBI Report error screen shows. I can't seem to find an event in React or the PBI Report Component that I can hook into to "hide" the report component via CSS when the prop change happens until the new props report data are loaded so it makes a smoother user experience. Do you have any recommendations here?

**Comment by akshay5995** [comment]
@nissan 
Let me get some clarifications here .
Do you mean your component makes an AJAX call to get a new Embed-Token for each report using the Aad-Token of the user that's logged in ?

And you manage the configuration's being passed into ReportComponent(powerbi-report-compoenent) in your wrapping component's state ?

Can you provide a code snippet ?

**Comment by nissan** [comment]
So this is how the report is rendered 
```
<Report
  key={this.state.pbiToken.token} // this allows a re-render when new report loaded
  embedType="report" // "dashboard"
  tokenType="Embed" // "Aad"
  accessToken={this.state.pbiToken.token} // access token goes here
  embedUrl={this.state.embedUrl} // embedUrl goes here
  embedId={this.state.reportId} // report or dashboard id goes here
  extraSettings={extraSettings}
  permissions="View" // "All"
  style={reportStyle}
  onLoad={this.handleReportLoad}
  onSelectData={this.handleDataSelected}
  onPageChange={this.handlePageChange}
/>
```

and these are how it gets its values
```
public componentDidMount() {
    getPbiDashboardById(this.props.id)  // does a lookup in custom DB for PBI Report values
      .then((result: IPbiItem) => {
        this.setState({ groupId: result.groupId, reportId: result.reportId });
      })
      .then(() => {
        this.getAccessToken() //gets the Windows identity access token needed to get the PBI token
          .then((token: ITokenData) => {
            this.setState({ token });
          })
          .then(() => {
            this.getPbiReportAccessToken(  //gets the PBI access token
              this.state.token.access_token,
              this.state.reportId,
              this.state.groupId
            ).then((pbiToken: IPbiTokenData) => {
              this.setState({ pbiToken });
            });
          });
      });
  }
```
this will work on the initial page load. When a new report is selected, the prop for ID changes, so componentDidUpdate will update this, and the related state values like this
```
public componentDidUpdate(prevProps: IPowerBiReportViewerProps) {
    if (prevProps.id !== this.props.id) {
      getPbiDashboardById(this.props.id)
        .then((result: IPbiItem) => {
          this.setState({ groupId: result.groupId, reportId: result.reportId });
        })
        .then(() => {
          this.getAccessToken()
            .then((token: ITokenData) => {
              this.setState({ token });
            })
            .then(() => {
              this.getPbiReportAccessToken(
                this.state.token.access_token,
                this.state.reportId,
                this.state.groupId
              ).then((pbiToken: IPbiTokenData) => {
                this.setState({ pbiToken });
              });
            });
        });
    }
  }
```
Now this works, and the new report loads, however there is a few seconds after the user clicks an on page link in a menu component that fires off the new route with the new prop value for ID where the `<Report />` component will show the PBI no data screen. I would like to intercept before this happens and hide the non-rendering screen via css (`display:block`) and (`display:none`) tags but there is a constant flickering if I wrap `<Report>` in a <div> with this, so I am wondering if there is an event that fires that I can insert this into that is more approrpiate. Any advice here?

**Comment by akshay5995** [comment]
@nissan 

As you are getting the accessToken directly into your component 

`
 this.getAccessToken()
            .then((token: ITokenData) => {
              this.setState({ token });
            })
`
Why don't you try something like 

`
<Report
  embedType="report" // "dashboard"
  tokenType="Aad" 
  accessToken={this.state.token} //use Aad token instead
  embedUrl={this.state.embedUrl}
  embedId={this.state.reportId} 
  extraSettings={extraSettings}
  permissions="View" 
  style={reportStyle}
  onLoad={this.handleReportLoad}
  onSelectData={this.handleDataSelected}
  onPageChange={this.handlePageChange}
/>
`

Then you can just same logic for switching state.embedUrl and state.reportId when you get the new props.

Will help you avoid a call to your service every time you switch reports and hopefully solve this issue.

**Comment by akshay5995** [comment]
Got it.
I've had a similar use case and used the Aad approach, it worked like a charm.
I would suggest you to try that approach too.

But, I believe you can accomplish what you are asking for in your wrapping component by introducing two more state properties to your component  **fetching** and **fetched** and setting them during your async calls to get your pbiToken.

```
this.state = {
     ....
        fetching: true, 
        fetched: false,
     ....
}
```

```
public componentDidMount() {
    getPbiDashboardById(this.props.id)  // does a lookup in custom DB for PBI Report values
      .then((result: IPbiItem) => {
        this.setState({ 
          groupId: result.groupId,
          reportId: result.reportId,
         });
      })
      .then(() => {
        this.getAccessToken() //gets the Windows identity access token needed to get the PBI token
          .then((token: ITokenData) => {
            this.setState({ token });
          })
          .then(() => {
            this.getPbiReportAccessToken(  //gets the PBI access token
              this.state.token.access_token,
              this.state.reportId,
              this.state.groupId
            ).then((pbiToken: IPbiTokenData) => {
              this.setState({ 
                pbiToken,
                fetching: false,
                fetched: true,
                });
            });
          });
      });
  }

```

```
public componentDidUpdate(prevProps: IPowerBiReportViewerProps) {
    if (prevProps.id !== this.props.id) {
      getPbiDashboardById(this.props.id)
        .then((result: IPbiItem) => {
          this.setState({ 
             groupId: result.groupId, 
             reportId: result.reportId,
             fetching: true,
             fetched: false,
          });
        })
        .then(() => {
          this.getAccessToken()
            .then((token: ITokenData) => {
              this.setState({ token });
            })
            .then(() => {
              this.getPbiReportAccessToken(
                this.state.token.access_token,
                this.state.reportId,
                this.state.groupId
              ).then((pbiToken: IPbiTokenData) => {
                this.setState({ 
                   pbiToken, 
                   fetching: false,
                   fetched: true,
                });
              });
            });
        });
    }
  }
```

In your render function:

```
const { fetching, fetched } = this.state;

return (
   <div className="root">
     {
          (fetching && !fetched) . && <div className"loader">Loading..</div> 
      }
     {
         (!fetching && fetched) &&
        <Report
            embedType="report"
            tokenType="Embed"
            accessToken={this.state.pbiToken.token}
            embedUrl={this.state.embedUrl}
            embedId={this.state.reportId}
            extraSettings={extraSettings}
            permissions="View" // "All"
            style={reportStyle}
            onLoad={this.handleReportLoad}
            onSelectData={this.handleDataSelected}
            onPageChange={this.handlePageChange}
          />
     }
   </div>
);
```

This should take care of replacing your ```<Report>``` from your DOM with some loader until you have all the config necessary to render the Report without any error.

**Comment by nissan** [comment]
Awesome! This worked like a charm! Thanks for the help! And for the awesome component.
