### ISSUE TITLE
How to capture Link clicked event

### ISSUE THREAD

**Issue by neerajnarayanankp** [akshay5995/powerbi-report-component#301]
i need to listen to a  **Link clicked event** from powerbi-report-component. But from the documentation of pbi report component , i could not find any useful explanation on how to do the same.
But in the official documentation i could find the [link](https://github.com/microsoft/PowerBI-JavaScript/wiki/Link-clicked-event) 
Use case is ,i have a power-bi-rpeort with a link to an external report which opens in a new tab.so on click of the button, i need to fetch the report details of the newly opened report.

Does powerbi-report-component have such a event for capture that?

**Comment by muthu1712** [comment]
@neerajnarayanankp 
The [powerbi-js](https://github.com/Microsoft/PowerBI-JavaScript) library which is used by this library has the event `dataHyperlinkClicked`, that gets triggered only when a table data represented as a URL is clicked.
It doesn't have any event handlers for links clicked apart from it.
