### ISSUE TITLE
Difference between powerbi-report-component and powerbi-client-react

### ISSUE THREAD

**Issue by Tzvetelin88** [akshay5995/powerbi-report-component#330]
Hello what is the main difference between this library and official one: https://github.com/microsoft/powerbi-client-react ?
The official one actually is just doing Iframe and not real React component integration, whish is very bad.

**Comment by akshay5995** [comment]
@Tzvetelin88  Both use `powerbi-client` client internally. This library is an unofficial wrapper whereas that's from microsoft. 

I just created react-y components which are easier to use and have better contract exposed as props.
