### ISSUE TITLE
Not able to bootstrap and preload report using this component

### ISSUE THREAD

**Issue by nitishkr** [akshay5995/powerbi-report-component#374]
Hi , 

I am not able to preload and boostrap my power bi report using this component for improving performance. Please help .

**Comment by akshay5995** [comment]
@nitishkr sorry for the delayed response. Can you please explain in detail.

**Comment by nitishkr** [comment]
@akshay5995 : How can we achieve this functionality [power bi bootstrap](https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/bootstrap-better-performance) using this package.

**Comment by akshay5995** [comment]
This package doesn't have that functionality yet. I'll covert this into a feature request and try to adopt it. 

Given that consumers might hit edge cases I'll try to export it as a different component so that we don't break existing contracts.

Thanks

**Comment by akshay5995** [comment]
This package doesn't use `bootstrap` use `embed` instead internally - I'd like to understand more on how you're planning to use it. For example what's the requirement to use `bootstrap`: 

Are you trying to do an ajax call to say get your `embedToken` or `reportType` and you'd like to use the bootstrap on component load base structure and then load report once your ajax call completes ?

**Comment by akshay5995** [comment]
@nitishkr You can try this new feature and let me know the feedback https://github.com/akshay5995/powerbi-report-component#usebootstrap
