### ISSUE TITLE
CSP issue on Report component Render

### ISSUE THREAD

**Issue by brunohsn6** [akshay5995/powerbi-report-component#380]
When i try to render my PowerBI Report component on production environment, I face this error:

Refused to frame 'https://app.powerbi.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by akshay5995** [comment]
@brunohsn6  The iframe is generated by the [powerbi-js](https://github.com/Microsoft/PowerBI-JavaScript) library which is used by this library.

**Comment by akshay5995** [comment]
@muthu1712 can you take a look if we can do something to help pass different CSP setting to iframe ?

**Comment by brunohsn6** [comment]
Yea, i've solved my issue making a different configuration on my server property configs! Initially I thought that those flags should be at the iframe tag, but I was able to fix it on my application! Thanks tho!
