### ISSUE TITLE
Is there a way to render the Power Bi Report to take up entire window? 

### ISSUE THREAD

**Issue by glenrage** [akshay5995/powerbi-report-component#4]
In the demo when I click "RUN", the power bi report is rendered only half the size of the window. If I go into edit mode, I can then make it larger. Is there any way to render the report to take up the full window upon initial rendering?

**Comment by akshay5995** [comment]
@glenrage Yes, you can pass in the styles to the report-component to make it take up the entire window.

I'm currently passing in : 

```
style={{
      height: '50%',
      border: '0',
      background: '#eee'
 }}
```

Is this question specific to the demo site or a feature request for the demo site?

**Comment by akshay5995** [comment]
@glenrage  I've added a button to toggle the display of config controls of the demo page.

I'm passing in the height of the report dynamically in styles to do the change. Please look into the images for reference.

_Show/Hide Config_ button can be found at the **top right corner** of the page.

![image](https://user-images.githubusercontent.com/13801224/47421808-fd57e280-d79e-11e8-8628-40ae1ed3d01e.png)

![image](https://user-images.githubusercontent.com/13801224/47422003-5889d500-d79f-11e8-81e3-7e323f027769.png)

**Comment by glenrage** [comment]
Ah ok, I see that it opens full screen now. I think I need to expand the size of my container. ANyways thanks for the help and for creating this nice package! Cheers!

**Comment by akshay5995** [comment]
Thanks !  Closing the issue
