### ISSUE TITLE
Is it possible to select the report page?

### ISSUE THREAD

**Issue by dikoga** [akshay5995/powerbi-report-component#45]
At the raw já client it is possible but I couldn’t find an exposed property to do so.

It is the page name here: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details

**Comment by akshay5995** [comment]
You can do this by using the `report` object returned to you in `onLoad` callback function.

```
            onLoad={report => {
              this.report = report;
              console.log("Set active page");
              const page = this.report.page(
                "ReportSection1c45b5dc6513ae89b4e3" // This will be your page name
              );
              page.setActive();
            }} 

```

Caveat in this is that you should know the page name in advance :)

Find the page you want using this method to log all the pages available in your report.
 
```

this.report.getPages(pages => console.log(pages));

```

You can further refer to [this page](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Page-Navigation) from powerbi js docs.

Sorry for the delayed response @dikoga

**Comment by akshay5995** [comment]
Just released the new version of the package to support `pageName` to be passed in as a prop 

```js
<Report 
  embedType="report" // "dashboard"
  tokenType="Embed" // "Aad"
  accessToken="" // accessToken goes here
  embedUrl="" // embedUrl goes here
  embedId="" // report or dashboard Id goes here
  pageName="" // * NEW * set as current page of the report
  />
```

Hope this save you the trouble of accessing the report object's method. 


> You can do this by using the `report` object returned to you in `onLoad` callback function.
> 
> ```
>             onLoad={report => {
>               this.report = report;
>               console.log("Set active page");
>               const page = this.report.page(
>                 "ReportSection1c45b5dc6513ae89b4e3" // This will be your page name
>               );
>               page.setActive();
>             }} 
> ```
> 
> Caveat in this is that you should know the page name in advance :)
> 
> Find the page you want using this method to log all the pages available in your report.
> 
> ```
> 
> this.report.getPages(pages => console.log(pages));
> ```
> 
> You can further refer to [this page](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Page-Navigation) from powerbi js docs.
> 
> Sorry for the delayed response @dikoga . Hope this answers your question.

**Comment by dikoga** [comment]
awesome! thanks!
