### ISSUE TITLE
[BUG] Componente re-render always i change any state

### ISSUE THREAD

**Issue by Gustavoaz** [akshay5995/powerbi-report-component#72]
**Describe the bug**
Componente re-render always i change any state. I want re-render specific component in, not powerbi

**To Reproduce**
Change any state and component re-render

**Expected behavior**
Not re-render when i change some state

**Comment by akshay5995** [comment]
Hi @Gustavoaz, I've got a few questions:

1. What do you mean by any state ?
2. Where is your `Report` component placed on the DOM tree?  (If your `Report` is under some `Parent` component whose state is dynamic then your `Child` i.e, `Report` will re-render when the parent re-renders.)

**Comment by Gustavoaz** [comment]
Hi @akshay5995 

1. Any state on my specific component
2. Yes, my `Report` is under some `Parent`. 

I implemented method `shouldComponentUpdate` to stop with re-render and It worked. But i think this is not ideal solution.

**Comment by akshay5995** [comment]
React re-renders child component if the `Parent` component re-renders. What exactly is the issue with re-rendering ?. To solve this is why React has `shouldComponentUpdate` or `React.memo`. If I'm missing something please propose a solution.

**Comment by akshay5995** [comment]
Closing due to in activity
