### ISSUE TITLE
[BUG] Change to onLoad event breaks ability to retrieve page data

### ISSUE THREAD

**Issue by BenF-Lumedic** [akshay5995/powerbi-report-component#85]
My `embedType` is 'report' if that's helpful for context.

In the current version, with the event setup below, I can call `await report.getPages()` in my onLoad handler and I receive the pages.
```
      report.on('loaded', () => {
        if (onLoad) onLoad(report);
      });
```

It appears that [the change to onLoad](https://github.com/akshay5995/powerbi-report-component/commit/a3924b27fa96560433f76cd50831273bd2cee92d#diff-64981db73b0fca7589b13889cbc2193fR70) breaks my ability to pull any page data from the `report` object, as calling `await report.getPages()` in onLoad now fails silently.

Should this change only apply to `embedType === 'dashboard'`?

Can you provide any detail on the dashboard bug that this code change addresses?

**Comment by akshay5995** [comment]
Merged your PR should fix this issue @BenF-Lumedic

**Comment by BenF-Lumedic** [comment]
@akshay5995 Working great on my end, thanks!
