### ISSUE TITLE
[BUG] I am trying to use aad token to embed the report, but when the page renders I get error saying You need to request Author for access

### ISSUE THREAD

**Issue by sagnikm95** [akshay5995/powerbi-report-component#97]
**Describe the bug**
I am trying to use aad token to embed the report, but when the page renders I get error saying You need to request Author for access,
the user corresponding to the token has owner access on the record

![image](https://user-images.githubusercontent.com/25024356/68601722-e7f94780-04ca-11ea-8a65-20fcf6aac811.png)

**Comment by akshay5995** [comment]
@sagnikm95  Have you tried the same config in [Microsoft's demo site](https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html)

**Comment by akshay5995** [comment]
It's most likely that the user doesn't have access to the PowerBI resource. Re-verify that the user and password that you used to generate the AAD token has sufficient privileges to access the report you're trying to embedded.

**Comment by sagnikm95** [comment]
Thanks for getting back. I tried embedding the same in the demo site , but ended up getting the same error. The user which I used to generate the token is the owner of the report. Randomly few time the report is getting rendered. But most times I am faced with the access issue. I gave the AAD App all read permissions for the PowerBI App, is there any specific xustomization I need to do there ? Also the AUD for the decrypted AAD token is the AAD client ID itself, should  that matter ?

**Comment by tratohecho3** [comment]
For me this library worked perfectly to render the reports

**Comment by akshay5995** [comment]
@sagnikm95 I think as this is not concerned with the library implementation it cannot be considered a bug of the library. I would love to help you out please reach out to me by mail.

Please take a look [this video](https://www.youtube.com/watch?v=4KuyPNtVijo) on how AAD token/ Embed token can be generated.

@tratohecho3 Glad it helped you 👍

**Comment by sagnikm95** [comment]
Thanks @akshay5995 , reached out to you regarding the same,
