### ISSUE TITLE
[BUG] onRender callBack not working!

### ISSUE THREAD

**Issue by nniefei** [akshay5995/powerbi-report-component#98]
onRender  callBack not work!

**Comment by akshay5995** [comment]
@nniefei I'm not able to reproduce it on my side. Maybe be you can try these:

1. Using the right prop `onRender` callback with with the right signature
2. Update the package if you're on the older version
3. The prop/ feature only works for the type `report` and *not* `dashboard` make sure you're not trying on a `dashboard`
